// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dnsblockchain/dao/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the dao module.
type Params struct {
	// Duration of the voting period in number of blocks.
	VotingPeriodBlocks uint64 `protobuf:"varint,1,opt,name=voting_period_blocks,json=votingPeriodBlocks,proto3" json:"voting_period_blocks,omitempty"`
	// Minimum deposit required to submit a proposal. If zero, no deposit is required.
	ProposalSubmissionDeposit github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=proposal_submission_deposit,json=proposalSubmissionDeposit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"proposal_submission_deposit"`
	// Minimum percentage of YES votes (of the total voting power that voted, or total at snapshot)
	// for a proposal to pass. (e.g., "0.50" for 50%). Stored as string, validated as Dec in Go.
	MinYesThresholdPercent cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=min_yes_threshold_percent,json=minYesThresholdPercent,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_yes_threshold_percent"`
	// Denomination of the token used for voting power.
	VotingTokenDenom string `protobuf:"bytes,4,opt,name=voting_token_denom,json=votingTokenDenom,proto3" json:"voting_token_denom,omitempty"`
	// Duration in blocks for which voting power decays from full to zero.
	VotingPowerDecayDurationBlocks uint64 `protobuf:"varint,5,opt,name=voting_power_decay_duration_blocks,json=votingPowerDecayDurationBlocks,proto3" json:"voting_power_decay_duration_blocks,omitempty"`
	// Amount of voting tokens distributed as reward per block to (e.g., active validators).
	// If zero, this mechanism is disabled.
	ValidatorRewardVotingTokensAmount types.Coin `protobuf:"bytes,6,opt,name=validator_reward_voting_tokens_amount,json=validatorRewardVotingTokensAmount,proto3" json:"validator_reward_voting_tokens_amount"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e773e4449bbc7e5, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetVotingPeriodBlocks() uint64 {
	if m != nil {
		return m.VotingPeriodBlocks
	}
	return 0
}

func (m *Params) GetProposalSubmissionDeposit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.ProposalSubmissionDeposit
	}
	return nil
}

func (m *Params) GetVotingTokenDenom() string {
	if m != nil {
		return m.VotingTokenDenom
	}
	return ""
}

func (m *Params) GetVotingPowerDecayDurationBlocks() uint64 {
	if m != nil {
		return m.VotingPowerDecayDurationBlocks
	}
	return 0
}

func (m *Params) GetValidatorRewardVotingTokensAmount() types.Coin {
	if m != nil {
		return m.ValidatorRewardVotingTokensAmount
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "dnsblockchain.dao.v1.Params")
}

func init() { proto.RegisterFile("dnsblockchain/dao/v1/params.proto", fileDescriptor_4e773e4449bbc7e5) }

var fileDescriptor_4e773e4449bbc7e5 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x31, 0x6f, 0xd3, 0x40,
	0x18, 0x8d, 0x69, 0xa8, 0x84, 0x59, 0xc0, 0x8a, 0x50, 0x92, 0x4a, 0x4e, 0xda, 0x0a, 0x29, 0x42,
	0xe0, 0x6b, 0xe8, 0xc6, 0x46, 0xc8, 0x84, 0x18, 0x22, 0x53, 0x21, 0xc1, 0xc0, 0xe9, 0xec, 0x3b,
	0x25, 0xa7, 0xc4, 0xf7, 0x99, 0xfb, 0x2e, 0x2e, 0xf9, 0x0b, 0xb0, 0xf0, 0x13, 0x98, 0x99, 0x98,
	0xf9, 0x05, 0x1d, 0x3b, 0x22, 0x86, 0x82, 0x92, 0x01, 0x7e, 0x06, 0xba, 0x3b, 0xa7, 0x50, 0x09,
	0xb1, 0xd8, 0xd6, 0xbd, 0x77, 0xef, 0xbd, 0xef, 0xf9, 0x0b, 0xf7, 0xb9, 0xc2, 0x6c, 0x01, 0xf9,
	0x3c, 0x9f, 0x31, 0xa9, 0x08, 0x67, 0x40, 0xaa, 0x21, 0x29, 0x99, 0x66, 0x05, 0x26, 0xa5, 0x06,
	0x03, 0x51, 0xeb, 0x0a, 0x25, 0xe1, 0x0c, 0x92, 0x6a, 0xd8, 0x6d, 0x4d, 0x61, 0x0a, 0x8e, 0x40,
	0xec, 0x97, 0xe7, 0x76, 0x6f, 0xb3, 0x42, 0x2a, 0x20, 0xee, 0x59, 0x1f, 0xc5, 0x39, 0x60, 0x01,
	0x48, 0x32, 0x86, 0x82, 0x54, 0xc3, 0x4c, 0x18, 0x36, 0x24, 0x39, 0x48, 0xe5, 0xf1, 0x83, 0x2f,
	0xcd, 0x70, 0x77, 0xe2, 0xfc, 0xa2, 0xa3, 0xb0, 0x55, 0x81, 0x91, 0x6a, 0x4a, 0x4b, 0xa1, 0x25,
	0x70, 0xea, 0x6c, 0xb1, 0x1d, 0xf4, 0x83, 0x41, 0x33, 0x8d, 0x3c, 0x36, 0x71, 0xd0, 0xc8, 0x21,
	0xd1, 0xfb, 0x20, 0xdc, 0x2b, 0x35, 0x94, 0x80, 0x6c, 0x41, 0x71, 0x99, 0x15, 0x12, 0x51, 0x82,
	0xa2, 0x5c, 0x94, 0x80, 0xd2, 0xb4, 0xaf, 0xf5, 0x77, 0x06, 0x37, 0x1f, 0x76, 0x12, 0x9f, 0x21,
	0xb1, 0x19, 0x92, 0x3a, 0x43, 0xf2, 0x04, 0xa4, 0x1a, 0x1d, 0x9d, 0x5d, 0xf4, 0x1a, 0x9f, 0xbe,
	0xf7, 0x06, 0x53, 0x69, 0x66, 0xcb, 0x2c, 0xc9, 0xa1, 0x20, 0x75, 0x60, 0xff, 0x7a, 0x80, 0x7c,
	0x4e, 0xcc, 0xaa, 0x14, 0xe8, 0x2e, 0x60, 0xda, 0xd9, 0xfa, 0x3d, 0xbf, 0xb4, 0x1b, 0x7b, 0xb7,
	0xe8, 0x75, 0xd8, 0x29, 0xa4, 0xa2, 0x2b, 0x81, 0xd4, 0xcc, 0xb4, 0xc0, 0x19, 0x2c, 0xb8, 0x1d,
	0x25, 0x17, 0xca, 0xb4, 0x77, 0xfa, 0xc1, 0xe0, 0xc6, 0xe8, 0xd0, 0xfa, 0x7d, 0xbb, 0xe8, 0xed,
	0x79, 0x75, 0xe4, 0xf3, 0x44, 0x02, 0x29, 0x98, 0x99, 0x25, 0xcf, 0xc4, 0x94, 0xe5, 0xab, 0xb1,
	0xc8, 0xd3, 0x3b, 0x85, 0x54, 0x2f, 0x05, 0x9e, 0x6c, 0x35, 0x26, 0x5e, 0x22, 0xba, 0x1f, 0xd6,
	0x1d, 0x50, 0x03, 0x73, 0x61, 0xa7, 0x54, 0x50, 0xb4, 0x9b, 0x56, 0x38, 0xbd, 0xe5, 0x91, 0x13,
	0x0b, 0x8c, 0xed, 0x79, 0xf4, 0x34, 0x3c, 0xd8, 0xb6, 0x09, 0xa7, 0x42, 0x53, 0x2e, 0x72, 0xb6,
	0xa2, 0x7c, 0xa9, 0x99, 0xb1, 0x15, 0xd5, 0xdd, 0x5e, 0x77, 0xdd, 0xc6, 0x75, 0xb7, 0x96, 0x38,
	0xb6, 0xbc, 0x71, 0x4d, 0xab, 0x7b, 0x7e, 0x13, 0xde, 0xad, 0xd8, 0x42, 0x72, 0x66, 0x40, 0x53,
	0x2d, 0x4e, 0x99, 0xe6, 0xf4, 0xef, 0x28, 0x48, 0x59, 0x01, 0x4b, 0x65, 0xda, 0xbb, 0xfd, 0xe0,
	0xff, 0x85, 0x37, 0x6d, 0x01, 0xe9, 0xfe, 0xa5, 0x5a, 0xea, 0xc4, 0x5e, 0xfc, 0x09, 0x8f, 0x8f,
	0x9d, 0xd2, 0xa3, 0xc3, 0x5f, 0x1f, 0x7b, 0xc1, 0xbb, 0x9f, 0x9f, 0xef, 0x75, 0xaf, 0xae, 0xe8,
	0x5b, 0xb7, 0xa4, 0x7e, 0x63, 0x46, 0xc7, 0x67, 0xeb, 0x38, 0x38, 0x5f, 0xc7, 0xc1, 0x8f, 0x75,
	0x1c, 0x7c, 0xd8, 0xc4, 0x8d, 0xf3, 0x4d, 0xdc, 0xf8, 0xba, 0x89, 0x1b, 0xaf, 0x3a, 0xff, 0xba,
	0xe5, 0xfe, 0x63, 0xb6, 0xeb, 0x16, 0xef, 0xf8, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x33,
	0xcd, 0xb4, 0xfc, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.VotingPeriodBlocks != that1.VotingPeriodBlocks {
		return false
	}
	if len(this.ProposalSubmissionDeposit) != len(that1.ProposalSubmissionDeposit) {
		return false
	}
	for i := range this.ProposalSubmissionDeposit {
		if !this.ProposalSubmissionDeposit[i].Equal(&that1.ProposalSubmissionDeposit[i]) {
			return false
		}
	}
	if !this.MinYesThresholdPercent.Equal(that1.MinYesThresholdPercent) {
		return false
	}
	if this.VotingTokenDenom != that1.VotingTokenDenom {
		return false
	}
	if this.VotingPowerDecayDurationBlocks != that1.VotingPowerDecayDurationBlocks {
		return false
	}
	if !this.ValidatorRewardVotingTokensAmount.Equal(&that1.ValidatorRewardVotingTokensAmount) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ValidatorRewardVotingTokensAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.VotingPowerDecayDurationBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VotingPowerDecayDurationBlocks))
		i--
		dAtA[i] = 0x28
	}
	if len(m.VotingTokenDenom) > 0 {
		i -= len(m.VotingTokenDenom)
		copy(dAtA[i:], m.VotingTokenDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.VotingTokenDenom)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.MinYesThresholdPercent.Size()
		i -= size
		if _, err := m.MinYesThresholdPercent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ProposalSubmissionDeposit) > 0 {
		for iNdEx := len(m.ProposalSubmissionDeposit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProposalSubmissionDeposit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.VotingPeriodBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.VotingPeriodBlocks))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VotingPeriodBlocks != 0 {
		n += 1 + sovParams(uint64(m.VotingPeriodBlocks))
	}
	if len(m.ProposalSubmissionDeposit) > 0 {
		for _, e := range m.ProposalSubmissionDeposit {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = m.MinYesThresholdPercent.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.VotingTokenDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.VotingPowerDecayDurationBlocks != 0 {
		n += 1 + sovParams(uint64(m.VotingPowerDecayDurationBlocks))
	}
	l = m.ValidatorRewardVotingTokensAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPeriodBlocks", wireType)
			}
			m.VotingPeriodBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPeriodBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalSubmissionDeposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposalSubmissionDeposit = append(m.ProposalSubmissionDeposit, types.Coin{})
			if err := m.ProposalSubmissionDeposit[len(m.ProposalSubmissionDeposit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinYesThresholdPercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinYesThresholdPercent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingTokenDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VotingTokenDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingPowerDecayDurationBlocks", wireType)
			}
			m.VotingPowerDecayDurationBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VotingPowerDecayDurationBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorRewardVotingTokensAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorRewardVotingTokensAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
