version: 1
validators:
- name: alice
  bonded: 100000000udns # Alice stakes 100 udns (100 millones de udns)
- name: bob
  bonded: 100000000udns   # Bob stakes 100 udns
accounts:
- name: alice
  coins:
  - 200000000udns # Alice starts with 200 udns
- name: bob # Bob también será el faucet
  coins:
  - 1100000000udns # 100M iniciales + 1000M para el faucet = 1.1B udns
faucet:
  name: bob # Especifica que bob es el nombre de la cuenta del faucet
  coins: # Esto indica cuánto puede dispensar el faucet por solicitud, no su balance inicial
  - 100000udns
genesis:
  app_state:
    staking:
      params:
        bond_denom: udns # El token para staking es 'udns'
    bank: {} # Dejar vacío o eliminar. Ignite CLI poblará balances y supply desde 'accounts' y 'validators'.
             # Si necesitas balances específicos para módulos, los añades aquí.
    gov:
      params:
        min_deposit:
          - denom: udns # Depósito mínimo para propuestas de gobernanza SDK
            amount: "10000000" # 10 udns
        voting_period: "172800s" # 2 días
    # Añadir la configuración para los parámetros del módulo DAO
    dao:
      params:
        voting_period_blocks: "500" # Ejemplo, igual al default
        proposal_submission_deposit:
          - denom: "udns"
            amount: "10000000" # Ejemplo, igual al default
        min_yes_threshold_percent: "0.500000000000000000" # Ejemplo, igual al default
        voting_token_denom: "udns" # Asegúrate que sea tu token único
        voting_power_decay_duration_blocks: "100" # Para pruebas, igual al default
        validator_reward_voting_tokens_amount:
          denom: "udns"
          amount: "0" # Ejemplo, igual al default
        add_tld_proposal_cost:
          - denom: "udns"
            amount: "5000000" # Ejemplo, igual al default
        quorum_percent: "0.334000000000000000" # Ejemplo, quórum del 33.4%
  chain_id: dnsblockchain