version: 1
accounts:
  - name: alice # Genesis validator / Initial account
    coins:
      - 14000000000udns # 4k liquid + 10k for bonding (total 14k dns)
  - name: bob # Faucet / Initial community account / Genesis validator
    coins:
      - 40000000000udns # 30k liquid + 10k for bonding (total 40k dns)

validators:
  - name: alice
    bonded: 10000000000udns # 10k dns
  - name: bob
    bonded: 10000000000udns # 10k dns

faucet:
  name: bob
  coins:
    - 100000udns # 0.1 dns per request
  host: "0.0.0.0:4500"

genesis:
  chain_id: "dnschain-mainnet-1"
  app_state:
    gov:
      params:
        min_deposit:
          - denom: "udns"
            amount: "50000000" # 50 dns
        max_deposit_period: "1209600s"
        voting_period: "1209600s"
        quorum: "0.334000000000000000"
        threshold: "0.500000000000000000"
        veto_threshold: "0.334000000000000000"
        min_initial_deposit_ratio: "0.000000000000000000"
        proposal_cancel_ratio: "0.500000000000000000"
        proposal_cancel_dest: ""
        expedited_voting_period: "86400s"
        expedited_threshold: "0.667000000000000000"
        expedited_min_deposit:
          - denom: "udns"
            amount: "100000000"
        burn_vote_quorum: false
        burn_proposal_deposit_prevote: false
        burn_vote_veto: true
        min_deposit_ratio: "0.010000000000000000"
    dao:
      params:
        voting_period_blocks: "43200" # ~1 months with 60 seconds per block
        proposal_submission_deposit:
          - denom: "udns"
            amount: "50000000" # 50 dns
        add_tld_proposal_cost:
          - denom: "udns"
            amount: "50000000" # 50 dns
        min_yes_threshold_percent: "0.500000000000000000"
        voting_token_denom: "udns"
        voting_power_decay_duration_blocks: "259200" # ~6 months with 60 seconds per block
        validator_reward_voting_tokens_amount:
          denom: "udns"
          amount: "0"
        quorum_percent: "0.334000000000000000"
    dnsblockchain:
      params:
        domain_creation_fee:
          - denom: "udns"
            amount: "20000000"
      domain_list: []
      domain_count: "0"
      permitted_tlds:
        - "web3"
        - "free"